version: '3'
services:
  db: 
    image: mysql
    environment:
      - MYSQL_DATABASE=demo_website_db
      - MYSQL_USER=mohamed
      - MYSQL_PASSWORD=Mohamed@1234 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # persist a sql db even when container stops
  php:
    build: .
    volumes:
      - "./:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 8000:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306