version: '3'

services:

  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=demo_website_db
      - MYSQL_USER=mohamed
      - MYSQL_PASSWORD=Mohamed@1234 # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True

    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "8001:3306"

  php-apache:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - app-network
  
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8002:80
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_PORT=3306

volumes:
  db-data:

networks:
  app-network:
    driver: bridge

